### ISSUE TITLE
Keyboard hides drawer

### ISSUE THREAD

**Issue by LuegM** [maustinstar/swiftui-drawer#15]
Hello,
is there a way to change the position of the drawer when the keyboard appears ?
I have a search bar on the drawer and when I click in it, the keyboard covers the drawer.

This is my Code:
I would like to use the ".onTapGesture" to bring the drawer to the top position...
![image](https://user-images.githubusercontent.com/94018890/166168551-efd4a802-fbee-4d80-92c6-572cf6368148.png)

This is how it looks now.
![image](https://user-images.githubusercontent.com/94018890/166168574-b927f751-a30d-41c9-8794-6d146d1ce2eb.png)

Sorry, I'm still a noob with Swift and I am just learning it now. 🤓

**Comment by pr0tonion** [comment]
I havent worked with Swift in a long time, but i think you can observe the keyboard and move the drawer up when the keyboard has appeared. Did something similar with another solution. ChatGPT might have a solution
