### ISSUE TITLE
Programmatically set the current height & disable gestures

### ISSUE THREAD

**Issue by JamesSedlacek** [maustinstar/swiftui-drawer#16]
## Feature Request
I'd like to be able to programmatically set the height of the drawer.
I'd also like to be able to set whether or not the drawer can be moved.. without disabling everything within the drawer.

## Example use case:
A searchBar textField is tapped, then the drawer is set to the mid or high resting point (Animated).
The drawer is not able to be moved while the user is searching for something.

## Potential Solution:
This can be done with a binding variable "currentHeight" or possibly a closure?
Maybe have a isDrawerMoveable variable? To disable gestures.

**Comment by thealpa** [comment]
I solved this by resting the drawer on a state variable.

If you want the user to continue interacting with the drawer after you programmatically changed it, change the state variable to a single height, wait a fraction of a second in an async queue and change it back to your array containing your resting points or just keep it at a single value as long as you want to lock the drawer.

You can check my solution [here](https://github.com/thealpa/CVAG/blob/main/CVAG/Views/DrawerView.swift).

**Comment by JamesSedlacek** [comment]
Thank you! This solution worked for me.
