### ISSUE TITLE
Drawer doesn't work in 0.1.0

### ISSUE THREAD

**Issue by thealpa** [maustinstar/swiftui-drawer#7]
**Issue**

The title might be a bit ambiguous, but using version 0.1.0 I just can not get the drawer to work or appear at all. Downgrading to 0.0.3 makes all my drawers work again. Not sure whether I missed something obvious, but this can be easily reproduced:

**Steps to reproduce**
1. Create new SwiftUI project
2. Add swiftui-drawer as package dependency
3. Add `import Drawer` to ContentView.swift
4. Add Drawer of choice to a ZStack in Body

<img width="1040" alt="Screen Shot 2020-09-03 at 16 48 01" src="https://user-images.githubusercontent.com/16319455/92130623-3c2c3a00-ee05-11ea-9fe6-72d174d1ced5.png">

**Comment by maustinstar** [comment]
I remember running into this issue a while back and I think it was due to a SwiftUI behavior difference between the iOS 13 sdk and iOS 14. At the time, I was more concerned with delivering for iOS 13.

I saw your PR #9, and I will review it to make sure it works on both iOS versions. Thanks!

**Comment by otymartin** [comment]
@thealpa @maustinstar This is still not working on iOS 14 Xcode 12.5

*Update*
It works if I manually drag the source files into the project but not if I add the library using SPM

**Comment by tobischw** [comment]
I am still running into this. Nothing appears in the preview when installing using SPM.

**Comment by xremix** [comment]
Unfortunately I'm running into the same problem :(

**Comment by xremix** [comment]
@thealpa @otymartin @tobischw this seem to be working through SPM if you just copy and past the latest commit SHA into Xcode, instead of automatically using the latest version.

**Comment by maustinstar** [comment]
@xremix, Does this work if you set the package version to "master" branch? I can release a new versioned tag from master if that works.

**Comment by xremix** [comment]
@maustinstar here we go! That works
